### ISSUE TITLE
npm run dev missing script: "dev"

### ISSUE THREAD

**Issue by jforaker** [zalmoxisus/crossbuilder#30]
`npm run dev` missing script: "dev"

![image](https://cloud.githubusercontent.com/assets/2042031/12970423/a7e704e4-d05c-11e5-9ffc-79a5a1a6e0ae.png)

**Comment by zalmoxisus** [comment]
@jforaker, thanks, I will fix the README. You should run `npm start`.

**Comment by ns04stars** [comment]
I am getting the same error not able to resolve it
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2

npm ERR! missing script: dev
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by zalmoxisus** [comment]
@ns04stars, as stated above, you should use `npm start`. Where did you find any references to `npm run dev`?

**Comment by yanlee26** [comment]
not perfect yet...npm ERR! missing script: start

**Comment by Olatunji-Longe** [comment]
Why is this issue closed??... I just encountered the same error

@zalmoxisus ...following instructions from the official electron github page; [see the link here](https://github.com/electron/electron-api-demos#readme)

![npm-issue](https://user-images.githubusercontent.com/5619338/27688821-e194df7c-5cd3-11e7-9831-5e455d1ec496.png)

**Comment by niloralab** [comment]
exactly I have same issue and searched a lot but couldn't find solution:(

**Comment by felipepatricio** [comment]
Try to put this code in your package.json `"scripts": {
    "dev": "webpack-dev-server --progress --colors --inline --hot"
  },`. 

Replace the "test: ..." with "dev: ..."

**Comment by noko966** [comment]
Hello guys i had same problem.
Was wrong doing npm commands from different folder,
 make sure u run commands from within your project folder.

**Comment by Sentrosi-Git** [comment]
Yep had same issue. Was in my client folder and not my server folder. Doh!

**Comment by gargvivek86** [comment]
Resolved by using below in package.json file.

 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "lite-server"
  },

**Comment by jdiegosierra** [comment]
Worked for me adding "dev": "lite-server" as @gargvivek86 said.

**Comment by loydbanks** [comment]
still not working for me, its showing an error when i add "dev":"lite-server"

**Comment by MajorQmz** [comment]
I met the same problem,how to solve it?

**Comment by yanlee26** [comment]
Not solved yet, you’d better choose another tools!

**Comment by Jennifercarmen** [comment]
solo trata de correr

npm install
npm run build && npm run serve

**Comment by acolmena26** [comment]
you guys need to add this to your scripts and that should work!
"scripts": {
    "start": "node app",
    "dev": "nodemon app"
  },

**Comment by CharlesLuttos** [comment]
If you are using @vue/cli npm run dev maybe won't work, instead it worked for me on old cli: npm install vue-cli which install cli 2.9.2

npm install vue-cli => npm run dev
npm install @vue/cli => npm start

**Comment by Siddharth77** [comment]
Let me help you out of this problem : 
Please go to your project and try running "npm run dev" 
if it throws error : Like mentioned above please run below command ,
**nano package.json 
or 
vi package.json**
and see if it has **not "dev"** task inside **"scripts"** as below , then please **see if it is in "start"** 
**"scripts": {
"build": "webpack --config webpack/webpack.config.prod.js  --colors",
"dev": "webpack-dev-server --open --config webpack/webpack.config.dev.js"
}**
or
**"scripts": {
"build": "webpack --config webpack/webpack.config.prod.js  --colors",
"start": "webpack-dev-server --open --config webpack/webpack.config.dev.js"
}**
Then **run** command like **npm run dev** or **npm run start** based on it.
Hope it will help. Mark it as resolved if it answered query. 
Please suggest for improvements, appreciated! .

**Comment by BitaShamsafar** [comment]
instead of npm run dev use "npm run serve"

**Comment by raiboudono** [comment]
因果関係わかりませんが、routerを直接installしてから実行したらvue init webpackが実行できるようになり、npm run devもできるようになりました。

**Comment by gityaso** [comment]
may be your are in the wring directory

**Comment by ajmeier29** [comment]
For anyone landing here in 2019, I was using pluralsight and the instructor tells you to use `npm run dev`, as the comments suggested above, the command is actually `npm run start`

**Comment by IsraelFelix** [comment]
> For anyone landing here in 2019, I was using pluralsight and the instructor tells you to use `npm run dev`, as the comments suggested above, the command is actually `npm run start`

Thank you so much. You are a God sent

**Comment by gsamad0** [comment]
> > For anyone landing here in 2019, I was using pluralsight and the instructor tells you to use `npm run dev`, as the comments suggested above, the command is actually `npm run start`
> 
> Thank you so much. You are a God sent

still have a problem after using the command: npm run start. pls help

**Comment by ndengangEdwin** [comment]
I had the same problem too. If you confirm that you are in the correct folder on your terminal, then just run
$ npm start
and the will solve the problem. I just got mine fixed

**Comment by AmosSpark** [comment]
npm run start

**Comment by Firdaus85** [comment]
![prob](https://user-images.githubusercontent.com/52103483/60382878-f0d80800-9a58-11e9-9fd7-f7f955d1eb2b.JPG)
I still have these problems after trying all these solutions

**Comment by Firdaus85** [comment]
npm install --save-dev webpack

npm install --save-dev webpack-dev-server

worked for me.

**Comment by robynpienaar** [comment]
> npm install --save-dev webpack
> 
> npm install --save-dev webpack-dev-server
> 
> worked for me.

Thank you so much - it worked a treat!

**Comment by russellfougere** [comment]
It's also mentioned in Pluralsights course "Javascript Fundamentals" by Mark Zamoyta

**Comment by alfonsojk** [comment]
only install nodemon and add this in your package.json:

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node app",
    "dev": "nodemon app"

**Comment by drrh12** [comment]
Check out if the vscode it's sending a warning that the content cannot be saved because it is a new file and compare to the older one, after this just save and run.

**Comment by DAlSantana** [comment]
> only install nodemon and add this in your package.json:
> 
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1",
> "start": "node app",
> "dev": "nodemon app"

Thanks Very Much !!!

**Comment by RaySoltani** [comment]
I would just like to add that I found this thread extremely helpful. Especially zalmoxisus' comments, which got me rolling through a tutorial that I'm currently working on. Thanks again!

**Comment by adirgapalit** [comment]
> @jforaker, thanks, I will fix the README. You should run `npm start`.

I still get issue when run `npm start`. I got error `missing script: start`

**Comment by laplace125** [comment]
> npm install --save-dev webpack
> 
> npm install --save-dev webpack-dev-server
> 
> worked for me.

Thanks, this worked for me

**Comment by LuoFalin** [comment]
try use "npm run serve"

**Comment by mahijendra** [comment]
I've tried legit every method that has been suggested here, and nothing is working out ffs :(

**Comment by DevSri02** [comment]
i have been facing this issue "Missing script dev" despite of writing in package.json   .....................................................................................Finally my solved only by saving the **_package.json_** and then "_overwrite_" it
