### ISSUE TITLE
Tried starting it per README and received an error

### ISSUE THREAD

**Issue by cymen** [zalmoxisus/crossbuilder#33]
I followed the README and when I access `https://localhost:3000/` using Chrome, there is an error on the console:

`Uncaught TypeError: storage.getAllKeys is not a function`

I did some debugging and it looks like if I replace `storage.getAllKeys` with `storage().getAllKeys`, it would work. This is in https://github.com/rt2zz/redux-persist/blob/master/src/getStoredState.js#L14. Do you indeed have 1.5.3 installed and working or are you on 2.x now?

**Comment by cymen** [comment]
(I forgot to say I'll look more this evening but wanted to open issue in case known.)

**Comment by zalmoxisus** [comment]
Yes, an issue appeared u the last `redux-perist`, fixed in next but not released yet.
Use `npm i --save redux-perist@next` for now.

**Comment by zalmoxisus** [comment]
@cymen, thanks for the report. Feel free to reopen the issue or create another one if still something goes wrong.

**Comment by cymen** [comment]
:+1: thank you
